### ISSUE TITLE
"_" symbol is not visible

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1076] opened 2019-01-16 21:57 UTC
## Electerm version:
26.0.14
## Operating system(linux, macos, or windows7/8/10?):
windows 10
## Expected Behavior

does not display the symbol "_"

## Current Behavior

show the symbol "_"
## Steps to Reproduce

![imagen](https://user-images.githubusercontent.com/28075454/51281213-c36a3700-19af-11e9-90e4-04ae37bc1326.png)

**Comment by zxdong262** [comment] 2019-01-17 00:14
Hi @saulperez2905 Can you try set different font family in settings?

**Comment by saulperez2905** [comment] 2019-01-17 04:47
Hi

 

please, could you tell me how to do it

 

De: ZHAO Xudong <notifications@github.com> 
Enviado el: miércoles, 16 de enero de 2019 19:15
Para: electerm/electerm <electerm@noreply.github.com>
CC: saulperez2905 <sael2905@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [electerm/electerm] "_" symbol is not visible (#1076)

 

Hi @saulperez2905 <https://github.com/saulperez2905>  Can you try set different font family in settings?

**Comment by saulperez2905** [comment] 2019-01-18 00:39
Hello
the tests were done.
Only the "_" symbol works when I use:

 



and the terminal looks like this:

 



 

 

De: ZHAO Xudong <notifications@github.com> 
Enviado el: jueves, 17 de enero de 2019 01:26
Para: electerm/electerm <electerm@noreply.github.com>
CC: saulperez2905 <sael2905@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [electerm/electerm] "_" symbol is not visible (#1076)

 

@saulperez2905 <https://github.com/saulperez2905>  Hi, click setting icon in left sidebar, settings, there is a font family setting, this will affect all session's default font setting, there are three fonts by default, you could set only one at a time, found out which one works, which one does not. you can edit ssh bookmark's font family setting in UI tab too, it will overrides defaults.

**Comment by zxdong262** [comment] 2019-01-18 00:51
@saulperez2905 Can't see images from emails.

**Comment by saulperez2905** [comment] 2019-01-18 00:55
Hi
tests were done. Only the "_" symbol works when I use:

![imagen](https://user-images.githubusercontent.com/28075454/51358570-c50c2b80-1a91-11e9-9d55-bcd5cbb8b065.png)

and the terminal looks like this:

![imagen](https://user-images.githubusercontent.com/28075454/51358590-e10fcd00-1a91-11e9-804f-e73fea338747.png)

**Comment by zxdong262** [comment] 2019-01-18 00:59
@saulperez2905 Thank you. I may try find out a solution tomorrow.

**Comment by saulperez2905** [comment] 2019-01-18 01:57
Thanks

**Comment by saulperez2905** [comment] 2019-01-21 15:22
Hello

I just downloaded the latest version (26.23) but the problem of "_" has not yet been requested

 

De: ZHAO Xudong <notifications@github.com> 
Enviado el: jueves, 17 de enero de 2019 20:00
Para: electerm/electerm <electerm@noreply.github.com>
CC: saulperez2905 <sael2905@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [electerm/electerm] "_" symbol is not visible (#1076)

 

@saulperez2905 <https://github.com/saulperez2905>  Thank you. I may try find out a solution tomorrow.

**Comment by zxdong262** [comment] 2019-01-22 00:30
@saulperez2905 Sorry, maybe next week.

**Comment by fwk1010** [comment] 2019-05-15 05:38
I had the same problem too. @zxdong262
![image](https://user-images.githubusercontent.com/10340097/57750783-2da0a780-7716-11e9-8fb8-78bd744fc2e4.png)
![image](https://user-images.githubusercontent.com/10340097/57750807-43ae6800-7716-11e9-9fbb-f205387fc73b.png)

**Comment by zxdong262** [comment] 2019-05-15 09:03
@fwk1010 Are you using a custom terminal theme?

**Comment by zxdong262** [comment] 2019-05-15 09:11
@fwk1010 Can you try set a different font family in settings?

**Comment by fwk1010** [comment] 2019-05-15 09:12
@zxdong262 Yeah.But it was no change when I use the default theme.
![image](https://user-images.githubusercontent.com/10340097/57763527-1bcdfd00-7734-11e9-9853-48037f998d7b.png)
Electerm version was 0.27.25 And Operating system was win10.

**Comment by zxdong262** [comment] 2019-05-15 09:17
@fwk1010 How it is looks like with a bright theme, can you share a screenshot of whole window, just curious.

**Comment by fwk1010** [comment] 2019-05-15 09:31
1.This screenshot was ssh(SECURE SHELL),it was right.
![image](https://user-images.githubusercontent.com/10340097/57764397-f3470280-7735-11e9-947b-645789636c68.png)

2.This was using default theme.
![image](https://user-images.githubusercontent.com/10340097/57764503-2c7f7280-7736-11e9-915b-0735e28a5702.png)

3.This was my custom theme that just changed the foreground and background.
![image](https://user-images.githubusercontent.com/10340097/57764716-97c94480-7736-11e9-8406-1f536de88afb.png)
![image](https://user-images.githubusercontent.com/10340097/57764749-a879ba80-7736-11e9-82f8-3b5f6bc33c59.png)
@zxdong262 Thank you for your prompt reply.

**Comment by fwk1010** [comment] 2019-05-15 09:33
> @fwk1010 Can you try set a different font family in settings?

I had no idea about this.What can I input? Mayby it is good way to select one or more.
![image](https://user-images.githubusercontent.com/10340097/57765132-73219c80-7737-11e9-8ffe-4e708947327e.png)

**Comment by zxdong262** [comment] 2019-06-11 01:52
@fwk1010 Sorry, missed the message, you can check the font name list from chrome browser setting, font family selection is not supported yet. Last time I check about this, it is quite complicated, I will check again. You may try adjust the order of these four default font family, still, I do not know the root cause yet, as I test this in new win10, it all works.

**Comment by zxdong262** [comment] 2019-06-11 01:54
@fwk1010 Any special Windows UI setting you can think of?

**Comment by zxdong262** [comment] 2019-12-26 00:58
has been a while, so close it now, feel free to reopen or submit new.

**Closed by zxdong262** 2019-12-26 00:58 UTC
Labels: Windows, bug
